In [1]:
import pandas as pd

In [2]:
# Load in files
df_schedule = pd.read_excel(r"C:\Users\Chris Napoli\OneDrive\Desktop\Github Repo\PaupackLaxStatTracking\Test_Data\DimSchedule.xlsx", sheet_name="DimSchedule")
df_players = pd.read_excel(r"C:\Users\Chris Napoli\OneDrive\Desktop\Github Repo\PaupackLaxStatTracking\Test_Data\DimPlayers.xlsx", sheet_name="DimPlayers")
df_fact = pd.read_excel(r"C:\Users\Chris Napoli\OneDrive\Desktop\Github Repo\PaupackLaxStatTracking\Test_Data\FactTable.xlsx", sheet_name="FactTable")

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Chris Napoli\\OneDrive\\Desktop\\Github Repo\\PaupackLaxStatTracking\\Test_Data\\FactTable.xlsx'

In [5]:
df_schedule

,Date,OpponentName,Won?,OppClearAtts,OppClearSuccesses,ClearAtts,ClearSuccesses,OppGoals,OppWomanUpAtts,OppWomanUpGoals,WomanUpAtts,OT?,FreePosAtt,FreePosGoal,OppWomanDownGoals
0,2025-03-08,Riverside HS,Y,18,12,22,18,5,4,1,6,N,3,1,0
1,2025-03-15,Lakewood HS,N,20,14,19,13,9,5,2,4,N,2,0,1
2,2025-03-22,Northview HS,Y,15,11,24,20,4,2,0,7,N,4,2,0
3,2025-03-29,Summit Academy,Y,17,10,21,17,6,3,1,5,Y,5,2,0
4,2025-04-05,Eastbrook HS,N,22,16,18,12,8,6,3,3,N,2,1,2
5,2025-04-12,Cedar Falls HS,Y,14,9,25,21,3,1,0,8,N,6,3,0
6,2025-04-19,Maplewood HS,Y,16,11,23,19,5,3,1,6,N,4,2,0

In [3]:
df_players

   PlayerID    PlayerName  JerseyNum  Position
0         1   Olivia Hart          3    Attack
1         2     Mia Russo          7    Attack
2         3   Emma Torres         11  Midfield
3         4    Sophie Kim         14  Midfield
4         5    Ava Nguyen         22  Midfield
5         6   Chloe Banks          5   Defense
6         7   Riley Patel          9   Defense
7         8   Jenna Walsh         18   Defense
8         9  Natalie Cruz          2   Defense
9        10  Lauren Scott          1    Goalie

In [4]:
df_fact

NameError: name 'df_fact' is not defined